spring.application.name=demo
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=hospitalDB;encrypt=true;trustServerCertificate=true
spring.datasource.username=khang
spring.datasource.password=123

spring.jpa.hibernate.ddl-auto=update